### ISSUE TITLE
Plugin autoloading

### ISSUE THREAD

**Issue by vesln** [vesln/hydro#10]
Wondering if this is a good idea... It will remove the need for hydro.conf.js in some cases, which is good. I'm not sure how we can make it work in the browsers which is a bit of a deal breaker. Thoughts?

**Comment by jkroso** [comment]
It would only be useful in node only projects since otherwise they will probably have some browser specific plugins which would cause an error if they were loaded in node.

**Comment by vesln** [comment]
In my latest app, I'm using ~12 hydro plugins. More or less all of them require some sort of manual configuration, although they provide sane defaults, so I don't think the autoloading will help a bunch. I think #13 will improve the overall experience. Also at some point we could agree on defaults (bdd syntax, hydro-dot as formatter, what-not) and be able to just `npm install hydro && hydro test/*`. [goodwin](https://github.com/logicalparadox/goodwin) is something I'm looking at as an example for the defaults.

**Comment by jkroso** [comment]
I think wrappers like goodwin are a good solution

**Comment by vesln** [comment]
Agreed, closing for now. I'm sure someday we'll get back to it.
