### ISSUE TITLE
Formatter interface

### ISSUE THREAD

**Issue by vesln** [vesln/hydro#11]
Currently, the formatters have a different interface than the normal plugins, which bugs me quite a bit. I'd be happy to unify it sooner than later, because my todo list with formatters is growing as crazy and later on it will be waaay more painful.

Accepting objections and arguments why this wouldn't be a good idea.

If you are wondering why they have a different interface we both gotta ask the crystal ball.

**Comment by jkroso** [comment]
I think just go a function. One less special case and will make it easy to use several reporters together since they will just be plugins.

**Comment by vesln** [comment]
True. I still think that we should keep the --formatter option and treat 'em as if they were something special, since otherwise the cli interface will become a bit obfuscated
