### ISSUE TITLE
issue with multiple errors thrown in single test

### ISSUE THREAD

**Issue by logicalparadox** [vesln/hydro#16]
Ok, this one is a bit strange. My given below will actually throw multiple errors in a single test during multiple ticks, however the reporter shows that other (possible passing) tests are failing with an error from the first test.

While display of multiple errors from a single test could be problematic, at very least only the first error should show for the first test and the other tests should report success.

``` js
// given.js
test('multiple errors', function(done) {
  for (var i = 0; i < 3; i++) {
    (function(ind) {
      setImmediate(function() {
        throw new Error('bad ' + i);
      });
    })(i);
  }
});

test('passing 1', function(done) {
  setTimeout(done, 10);
});

test('passing 2', function(done) {
  setTimeout(done, 10);
});
```

![screen shot 2014-01-12 at 9 23 00 am](https://f.cloud.github.com/assets/58988/1896315/14cc8ac6-7b95-11e3-88d1-c2c4cd97840a.png)

**Comment by vesln** [comment]
Agreed, the current behavior is broken for sure. I'll try to provide a fix as soon as possible

**Comment by vesln** [comment]
Could you please verify that this solves it?

[https://github.com/hydrojs/hydro/commit/3d2c9e4d28b753e1e914bd52d71f64ac8a1fdf80](https://github.com/hydrojs/hydro/commit/3d2c9e4d28b753e1e914bd52d71f64ac8a1fdf80)
