### ISSUE TITLE
Use facet for the configurations

### ISSUE THREAD

**Issue by vesln** [vesln/hydro#18]
[facet](https://github.com/qualiancy/facet) is a module by @logicalparadox that is basically a config mixin. It's very similar to what hydro implements. I'm thinking we can move the code related to configurations out of hydro, which will reduce the noise significantly.

In order to do this, I'd like to see the following features in facet:

• `push`
• `set` and `get` using [pathval](https://github.com/chaijs/pathval)
• IE8+ support

I have push access to all mentioned projects, and I'm sure @logicalparadox wouldn't mind giving access to anyone who is interested in helping out with this.

**Comment by logicalparadox** [comment]
:+1:
