### ISSUE TITLE
Test execution time doesn't include the excution time of the hooks

### ISSUE THREAD

**Issue by vesln** [vesln/hydro#27]
cc @jkroso

**Comment by jkroso** [comment]
hmm I think thats a good thing

**Comment by vesln** [comment]
IMHO it should include it, because the hooks are nothing but test setup and cleanup which can be inlined in the actual test.

I was running my end to end test after I extracted the exceution of HTTP requests into before hooks and suddenly everything became really fast :D

**Comment by jkroso** [comment]
yea but http requests can vary a lot in time and that would just add noise to the timing data. Hooks are the uninteresting part of the test.

And at the moment any errors in hooks kill everything btw so I hadn't really been considering them part of tests in general.

**Comment by hazeledmands** [comment]
Seems like we could keep track of the time spent in the test, as well as the time spent in setup and cleanup, and let reporters choose what to show?

**Comment by jkroso** [comment]
Yea all the data we would need to store would be hookStart, start, end, and hookEnd for the formatters to be able to present whatever they like
