### ISSUE TITLE
idea: nothing but test blocks

### ISSUE THREAD

**Issue by jkroso** [vesln/hydro#3]
I.E get rid of the `suite` function and just have a slightly overloaded `test` function. I think it would be nice to be able to make assertions anywhere within a test suite. If your not against the idea I'll make a PR in the next couple weeks.

**Comment by vesln** [comment]
I'm not sure if I understood your idea, but here is what you can accomplish currently:

``` js
// hydro.conf.js

hydro.set({
  suite: 'my-suite',
});
```

And then there is no need to call `addSuite` at all, everything will be added into 'my-suite'.

So you can easily have the following:

``` js
// my-test.js

test('foo', fn);
test('bar', fn);
```

Is this what you had in mind?

**Comment by jkroso** [comment]
No I'm thinking of switching the API from:

``` js
suite('my-thing', function(){
  test('it works', function(){
    // assertions
  })
})
```

to:

``` js
test('my-thing', function(){
  test('it works', function(){
    // assertions
  })
})
```

Actually though if everything was a test you would just write:

``` js
test('my-thing', function(){
  // assertions
})
```

Or actually I also like the idea of each file in a test suite being wrapped in an implicit `test(__filename, function(){ ... })` which would make this simple test suite just:

``` js
// assertions
```

but thats off topic now :)

**Comment by vesln** [comment]
Haha, that's awesome! I really like how similar ideas we have. I thought about the same and did https://github.com/hydrojs/hydro-file-suite

I'm interested in seeing your idea in action. However, I think it could easily be done as a plugin. Currently there is no docs (the project is still a secret hahah), but you can review some of the repos in the organization for guidelines.

Added you to the organization so feel free to go crazy with your ideas.

**Comment by jkroso** [comment]
actually I saw that repo the other day so thats maybe it was yours in the first place :).

Cool thanks for adding me. I'll get in touch when I've got something working.

**Comment by vesln** [comment]
Feel free to add me on skype (veselin.us) or send emails if needed. Happy to help with whatever I can.

**Comment by vesln** [comment]
Closing since as we discussed, we'll try to implement it as a plugin, initially.
