### ISSUE TITLE
integration tests fail node 0.11

### ISSUE THREAD

**Issue by logicalparadox** [vesln/hydro#4]
![screen shot 2013-12-21 at 9 07 41 am](https://f.cloud.github.com/assets/58988/1796039/89a4348c-6a4e-11e3-9960-9c6007a683b3.png)
- Node 0.11.9
- branch: master

I thought this might be `tryc` but it tests for this scenario (thrown error in setTimeout) and it all passes on Node 0.11.

Thoughts?

EDIT: Image says branch `refactor/cli` but this also occurs on master!

**Comment by vesln** [comment]
Confirmed by Travis. I still believe the problem is in `tryc`, so I will investigate further.
