### ISSUE TITLE
Merging configs

### ISSUE THREAD

**Issue by vesln** [vesln/hydro#6]
Now that we support multiple config files, we should decide whether `set` must merge the supplied configs or not.

The primary question for me is shown by this scenario:

```
$ hydro ---plugins foo --plugins bar # this will call .set implicitly
```

``` js
// hydro.conf1.js

hydro.set({ 
  plugins: ['baz', 'boo'] 
});
```

``` js
// hydro.conf2.js

hydro.set({ 
  plugins: ['something-different'] 
});
```

What would be the expected outcome in this scenario?

As a side note, currently, we have `push` and also `set`, that accepts setting a key/val pair of config object.

You can do the following:

``` js
hydro.set('globals', 'should', chai.should());
hydro.push('plugins', 'hydro-something');
```

This is how plugins modify the config values without overriding these set by the user.

CC:

@logicalparadox

**Comment by logicalparadox** [comment]
I added the deep merge utility to params so this shouldn't be too hard. 

I would say YES, `set` should merge the settings. For example, I have "goodwin" which loads a predefined template of configs then I load project specific configs. If I want to add more plugins I have to know what plugins goodwin loaded first. `push` is nice, but I would rather see `set` merge and then add an `unset` or `reset` if you wanted to overwrite a setting.

**Comment by vesln** [comment]
Fair point, agreed. Would you be interested in making the change, so `goodwin` can leverage it as nicely as possible?

**Comment by logicalparadox** [comment]
Just a thought... perhaps some should merge but some should not. For examples... `tests` should not merge but plugins should. 

Thoughts?

**Comment by vesln** [comment]
I'm a bit afraid that it may become a bit too complicated, although I understand where you are coming from. It's a tricky problem to tackle to be honest.
